name: lacrima
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  ######### Firebase Package #########
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  ######### Firebase Package #########
  #
  ########################################
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  sizer: ^3.0.4
  min_id: ^1.1.0
  im_stepper: ^1.0.1+1
  expandable: ^5.0.1
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.0.20
  flutter_bloc: ^8.1.6
  buildcondition: ^0.0.4
  shared_preferences: ^2.0.13
  multi_select_flutter: ^4.1.2
  flutter_local_notifications: ^17.2.3
  ########################################
  #
  ######## Native Splash Plugin ########
  flutter_native_splash: ^2.1.1
flutter_native_splash:
  ios: true
  android_12:
  android: true
  android_gravity: center
  ios_content_mode: center
  background_image: "assets/images/splash/Splash.png"
  ######## Native Splash Plugin ########
  #

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/App Logo/app_Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/App Logo/Logo2.png"
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - assets/images/App Logo/

  # fonts:
  #   - family: test
  #     fonts:
  #       - asset: assets/fonts/test.ttf
  #         style: italic
